---
title: "Lab-Linear Regression"
author: "Ravi Hela"
date: "26/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(ISLR)
library(car)

```
```{r}
names(Boston)

```
```{r}
lm.fit <- lm(medv ~ lstat, data = Boston)
lm.fit
```

```{r}
summary(lm.fit)
```

```{r}
names(lm.fit)
coef(lm.fit)
confint(lm.fit)
```
```{r}
predict(lm.fit, data.frame(lstat= c(5, 10, 15)), interval =  "confidence")
predict(lm.fit, data.frame(lstat= c(5, 10, 15)), interval =  "prediction")

```
```{r}
attach(Boston)
plot(lstat, medv)
abline(lm.fit)

```
```{r}
par(mfrow = c(2,2))
plot(lm.fit)

plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))

```
#Multiple Linear Regression

```{r}
lm.fit = lm(medv ~ lstat + age, data = Boston)
summary(lm.fit)
```

```{r}
lm.fit = lm(medv ~., data = Boston)
summary(lm.fit)

```

```{r}
vif(lm.fit)
lm.fit = lm(medv ~. -age, data = Boston)
summary(lm.fit)

```

```{r}
lm.fit1 <- update(lm.fit, ~.-age)

```

#interacation term
```{r}
summary(lm(medv ~ lstat * age, data = Boston)) #lstat * age implies lstat + agae + lstat:age

```
#Non-Linear transformation
```{r}
lm.fit2 <- lm(medv ~ lstat + I(lstat^2))
summary(lm.fit2)

```
#ANOVA on lm.fit and lm.fit2
```{r}
anova(lm.fit, lm.fit2)


```

#plot lm.fit2
```{r}
par(mfrow= c(2,2))
plot(lm.fit2)

```
#fitting multiple degree
```{r}

lm.fit5 <- lm(medv ~ poly(lstat, 5))
summary(lm.fit5)
```
#log transformation
```{r}
summary(lm(medv ~ log(rm)))


```

#qualitative oredictors

```{r}
names(Carseats)
```

```{r}
lm.fit <- lm(Sales ~ . + Income:Advertising + Price:Age, data = Carseats)
summary(lm.fit)

```
```{r}
attach(Carseats)
contrasts(ShelveLoc)

```

